front:
  build: .
  ports:
    - "88:80"
    - "443:443"
    - "9000:9000"
  links:
    - redis:redis
  volumes:
    - ./www:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs:/var/log/supervisor

redis:
  image: redis
  ports:
    - "6379:6379"
